CREATE DATABASE [CTW_DB]
ON
PRIMARY ( NAME=[CTW_DB],
FILENAME='D:\Database\MSSQL15.MSSQLSERVER\MSSQL\DATA\CTW_DB.mdf',
SIZE=6MB,
MAXSIZE=30MB,
FILEGROWTH=12%)
LOG ON
( NAME=[CTW_DBLog],
FILENAME= 'D:\Database\MSSQL15.MSSQLSERVER\MSSQL\DATA\CTW_DB.ldf',
SIZE=3MB,
MAXSIZE=22MB,
FILEGROWTH=17%)
COLLATE SQL_Latin1_General_Cp1_CI_AS

